CLIENT_ID='GET_YOUR_CLIENT_ID_FROM_ADMIN_CONSOLE'
CLIENT_SECRET='DEFINE_YOUR_SECRET'
ACCESS_TOKEN='GET_YOUR_ACCESS_TOKEN_FROM_ADMIN_CONSOLE'

BOX_RAW_DATA_FOLDER='pending'
BOX_PROCESSED_DATA_FOLDER='processed'

